main:
  dataset: True
  dataset_search: False

  siamese: True
  siamese_search: False

  classifier: True
  classifier_search: False

dataset:
  directory: ./VCTK-Corpus/wav48
  mode: mfcc # mfcc / spectogram
  mic: 2 # 1 = lower quality mic, 2 = high quality
  test_size: 0.2
  n_triplets: 100000
  n_speakers: 200
  n_recordings: 500
  sr: 22050
  length: 3 
  overlap: 0.25
  max_count: 10
  min_duration: 2.7
  n_mfcc: 40 
  n_mels: 128
  n_fft: 1024
  fmin: 0
  fmax: 11025
  power: 2
  top_db: 30

#best 512, 0.01
siamese:
  plot_history: False
  create_embedings: True
  plot_scatter: True
  
  result_name: final

  version: 1.1

  verbose: 1
  validation_split: 0.15 
  batch_size: 256
  dense: 512
  epochs: 50
  learning_rate: 0.01
  margin: 1 #triplet loss
  patience: 5 #early stopping

classifier:
  plot_summary: False
  plot_history: True
  plot_confusion: True

  result_name: final

  verbose: 2 
  validation_split: 0.15 
  batch_size: 256
  epochs: 1
  learning_rate: 0.001
  patience: 5 #early stopping
  